---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    rebase-strategy: auto
    schedule:
      interval: weekly
    reviewers:
      - georglauterbach
    assignees:
      - georglauterbach
    labels:
      - area/ci
      - kind/update

  - package-ecosystem: cargo
    directory: code
    target-branch: dev
    rebase-strategy: auto
    schedule:
      interval: weekly
    reviewers:
      - georglauterbach
    assignees:
      - georglauterbach
    labels:
      - area/dependencies
      - kind/update
