[workspace]

# Rust toolchain releases can be found under
# https://github.com/rust-lang/rust/blob/master/RELEASES.md

members = [
  "communication",
  "hardware",
  "kernel",
  "memory",
  "processes",
  "scheduling",
  "syscalls"
]

[profile.release]
lto = true
codegen-units = 1
