set shell             := [ "bash", "-eu", "-o", "pipefail", "-c" ]
set dotenv-load       := false

export ROOT_DIRECTORY := justfile_directory()

# show a dedicated help message
help:
	#! /bin/bash
	RUST_INSTALLED=true

	if command -v rustc &>/dev/null
	then printf 'tools\n├── ' ; rustc --version
	else
		printf "tools\n├── 'rustc' not installed or in \$PATH\n"
		RUST_INSTALLED=false
	fi

	if command -v cargo &>/dev/null
	then printf '├── ' ; cargo --version
	else printf "├── 'cargo' not installed or in \$PATH\n"
	fi

	printf '└── just  %s\n\n' "$(cut -d ' ' -f 2 < <(just --version))"

	just --list
	printf '\n'

# -----------------------------------------------
# ----  Build and Test  -------------------------
# -----------------------------------------------
