# For a reference to this file, see
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

# Rust toolchain releases can be found under
# https://rust-lang.github.io/rustup-components-history/

# Make sure to propagate version and component changes here to
# `.github/workflows/kernel_tests.yml` and to
# `.github/workflows/security.yml`!

# General information about the keys below can be found under
# https://rust-lang.github.io/rustup/concepts/index.html
[toolchain]
channel = 'nightly-2024-10-10'
components = [ 'cargo', 'rustc', 'rust-std', 'clippy', 'rustfmt' ]
targets = [
  'riscv64gc-unknown-none-elf',
  # 'aarch64-unknown-none'
]
