---
blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://georglauterbach.github.io/uncore/
    about: Read this project's documentation
  - name: Development Guidelines
    url: https://georglauterbach.github.io/uncore/development/
    about: Read this project's development standards and guidelines
  - name: Contributing Guidelines
    url: https://georglauterbach.github.io/uncore/community/code_of_conduct/
    about: Read this project's contributing standards and guidelines
