---
name: Feature Request
description: Request a new feature
title: 'feature request: '
labels:
  - area/features
  - kind/new feature
  - priority/low

body:
  - type: textarea
    id: request
    attributes:
      label: ':rocket: State Your Request'
      placeholder: I would like to see unCORE running on ARMv9. Is that possible?
    validations:
      required: true
