# For a reference to this file, see
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

# Rust toolchain releases can be found under
# https://rust-lang.github.io/rustup-components-history/

# Make sure to propagate version and component changes here to
# `.github/workflows/kernel_tests.yml` and to
# `.github/workflows/security.yml`!

[toolchain]
channel = "nightly-2023-06-25"
components = [ "cargo", "llvm-tools-preview", "rustc", "rustfmt", "rust-std", "rust-src" ]
