---
site_name: unCORE
site_description: unCORE Kernel Documentation
site_author: The unCORE Kernel Community
site_url: https://uncore-kernel.org

copyright: >
  <p>&copy <em>The unCORE Kernel Community</em><br/><span>
  This project is licensed under GPLv3.</span></p>

repo_name: unCORE
repo_url: https://github.com/georglauterbach/uncore

docs_dir: content/

nav:
  - Home: index.md
  - Development: development.md
  - Modules:
      - Overview: modules/modules.md
      - System Call Interface: modules/syscalls.md
      - Kernel: modules/kernel.md
      - Communication: modules/communication.md
      - Memory: modules/memory.md
      - Processes: modules/processes.md
      - Scheduling: modules/scheduling.md
      - Hardware Abstraction Layer: modules/hardware.md

theme:
  name: material
  language: en
  font: false
  logo: images/logo.ico
  favicon: images/logo.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.annotate
  palette:
    # light mode
    - media: '(prefers-color-scheme: light)'
      scheme: light
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: dark
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - docs-style.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/georglauterbach/uncore

  # We do not use `mike`, but enabling this will enable the version selector UI.
  # It references `versions.json` on `gh-pages` branch,
  # however we have a basic setup that only matches `version` to a subdirectory.
  version:
    provider: mike

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 2
      permalink: ⚓︎
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: yml
          lang: yaml
