---
site_name: unCORE
site_description: unCORE Kernel Documentation
site_author: The unCORE Kernel Community
site_url: https://georglauterbach.github.io/uncore/

copyright: >
  <p>&copy The <tt>unCORE</tt> Kernel Community. This project is licensed under GPLv3.</p>

repo_name: unCORE
repo_url: https://github.com/georglauterbach/uncore

docs_dir: content/

watch:
  - include

nav:
  - Home: index.md
  - Development: development.md
  - Kernel Architecture:
      - Overview: kernel_architecture/overview.md
      - RISC-V: kernel_architecture/risc_v.md
  - Testing: testing.md
  - Community:
      - Overview: community/overview.md
      - Changelog: community/changelog.md
      - Code of Conduct: community/code_of_conduct.md
      - Security: community/security.md
      - References and Sources: community/references_and_sources.md

plugins:
  - search
  - tags

theme:
  name: material
  language: en
  logo: images/logo.ico
  favicon: images/logo.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.annotate
    - content.code.copy
  palette:
    # automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # light mode
    - media: '(prefers-color-scheme: light)'
      scheme: light
      primary: blue
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/georglauterbach/uncore

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
  - toc:
      toc_depth: 3
      permalink: ⚓︎
  - pymdownx.snippets:
      url_download: true
      auto_append:
        - include/glossary.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: yml
          lang: yaml
