---
site_name: unCORE
site_description: unCORE Kernel Documentation
site_author: The unCORE Kernel Community
site_url: https://georglauterbach.github.io/uncore/edge/

copyright: >
  <p>&copy The <tt>unCORE</tt> Kernel Community. This project is licensed under GPLv3.</p>

repo_name: unCORE
repo_url: https://github.com/georglauterbach/uncore

docs_dir: content/

nav:
  - Home: index.md
  - Development: development.md
  - Kernel Architecture: kernel_architecture.md
  - Testing: testing.md
  - Community:
      - Overview: community/overview.md
      - Changelog: community/changelog.md
      - Code of Conduct: community/code_of_conduct.md
      - Security: community/security.md

plugins:
  - search
  - tags

theme:
  name: material
  language: en
  logo: images/logo.ico
  favicon: images/logo.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.annotate
  palette:
    # light mode
    - media: '(prefers-color-scheme: light)'
      scheme: light
      primary: teal
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/georglauterbach/uncore

  # We do not use `mike`, but enabling this will enable the version selector UI.
  # It references `versions.json` on `gh-pages` branch,
  # however we have a basic setup that only matches `version` to a subdirectory.
  version:
    provider: mike
    default: edge

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 2
      permalink: ⚓︎
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: yml
          lang: yaml
