#![no_std]
#![no_main]
#![deny(clippy::all)]
#![deny(clippy::nursery)]
#![deny(clippy::pedantic)]
#![feature(custom_test_frameworks)]
#![test_runner(helper::test::test_runner)]
#![reexport_test_harness_main = "__start_tests"]
