---
name: Check the Documentation

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches: ['**']
    paths:
      - .github/workflows/documentation.yml
      - documentation/**

defaults:
  run:
    shell: bash

jobs:
  check-successful-build:
    name: Test if documentation can be build
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build with mkdocs-material with Docker
        run: scripts/documentation.sh build
