---
name: Code / Security

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 6

permissions:
  contents: read

jobs:
  cargo-audit:
    name: Audit dependencies
    uses: georglauterbach/uncore/.github/workflows/generic_code_executor.yml@master
    with:
      command: cargo audit --deny warnings
