---
name: Code Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/code_tests.yml
      - code/**
    branches: ['**']
  push:
    paths: [code/**]
    branches: [master]

defaults:
  run:
    working-directory: code

jobs:
  kernel-linting:
    name: Lint the kernel code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run:  ../.github/scripts/install_rust.sh

      - name: Run all checks
        run: >-
          cargo run -- -vv check

  unit-and-integration-tests:
    name: Run unit- and integration-tests
    runs-on: ubuntu-22.04
    needs: kernel-linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        run:
          apt-get -y install --no-install-recommends qemu-system-riscv64

      - name: Install Rust
        run:  ../.github/scripts/install_rust.sh

      - name: Run all unit-test
        run: >-
          cargo run -- -vv u-test

      - name: Run all integration-tests
        run: >-
          cargo run -- -vv u-test
