---
name: Code / Tests & Checks

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/code_tests_and_checks.yml
      - code/**
    branches: ['**']
  push:
    paths: [code/**]
    branches: [master]

permissions:
  contents: read

jobs:
  kernel-linting:
    name: Lint the kernel code
    uses: georglauterbach/uncore/.github/workflows/generic_code_executor.yml@master
    with:
      install-sccache: true
      command: cargo run -- -vv check

  unit-and-integration-tests:
    name: Run unit- and integration-tests
    uses: georglauterbach/uncore/.github/workflows/generic_code_executor.yml@master
    with:
      install-qemu: true
      install-sccache: true
      command: cargo run -- -vv u-test && cargo run -- -vv i-test
