---
name: Code / Linting

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ['**']

jobs:
  linting:
    name: Run SuperLinter
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code base
        uses: super-linter/super-linter/slim@v5.6.1
        env:
          LOG_LEVEL: NOTICE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: true

          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
