---
# gratefully copied and adjusted from docker-mailserver/docker-mailserver
name: Documentation

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - documentation/**
    tags:
      - '[0-9]+.[0-9]+*'

defaults:
  run:
    shell: bash

env:
  DOCS_VERSION: edge
  # Assign commit authorship to official Github Actions
  # bot when pushing to the `gh-pages` branch:
  GIT_USER: github-actions[bot]
  GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  deployment:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check if deploy is for a `v<major>.<minor>` tag version instead of `edge`
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: documentation
        run: |
          DOCS_VERSION=$(grep -oE 'v[0-9]+\.[0-9]+' <<< "${GITHUB_REF}")
          echo "DOCS_VERSION=${DOCS_VERSION}" >> "${GITHUB_ENV}"
          # Docs should build referencing the tagged version instead:
          sed -i "s|^\(site_url:.*\)edge|\1${DOCS_VERSION}|" config.yml

      - name: Build with mkdocs-material with Docker
        run: scripts/documentation.sh build

      - name: If a tagged version, fix canonical links and remove `404.html`
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: documentation/site
        # 404 is not useful due to how Github Pages implement custom 404 support:
        # (Note the edge 404.html isn't useful either as it's not copied to
        # the `gh-pages` branch root)
        #
        # Replace the tagged '${DOCS_VERSION}' in the 'canonical' link element of HTML files,
        # to point to the 'edge' version of documentation as the authoritative source:
        run: |
          rm 404.html
          find . -type f -name "*.html" -exec \
            sed -i "s|^\(.*<link rel=\"canonical\".*\)${DOCS_VERSION}|\1edge|" {} +

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build directory contents to publish to the `gh-pages` branch:
          publish_dir: ./documentation/site
          # Directory to place `publish_dir` contents on the `gh-pages` branch:
          destination_dir: ${{ env.DOCS_VERSION }}
          user_name: ${{ env.GIT_USER }}
          user_email: ${{ env.GIT_EMAIL }}

  add-version-to-documentation:
    name: Update `versions.json` if necessary
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    needs: deployment
    steps:
      - name: Checkout the tagged commit (shallow clone)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout the documentation deployment branch to a subdirectory
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Updates `env.DOCS_VERSION` to the tag version; if invalid exits job early.
      - name: Ensure `versions.json` has `v<major>.<minor>` substring from tag name
        id: add-version
        continue-on-error: true
        working-directory: gh-pages
        run: ../scripts/documentation.sh update_versions_json

      # If an actual change was made to `versions.json`, commit and push it.
      # Otherwise the step is skipped instead of reporting job failure.
      - name: Push update for `versions.json`
        if: ${{ steps.add-version.outcome == 'success' }}
        working-directory: gh-pages
        run: |
          git config user.name ${{ env.GIT_USER }}
          git config user.email ${{ env.GIT_EMAIL }}
          git add versions.json
          git commit -m "chore: Add ${{ env.DOCS_VERSION }} to version selector list"
          git push
