---
# gratefully copied and adjusted from docker-mailserver/docker-mailserver
name: Documentation

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - .github/workflows/documentation.yml
      - documentation/**
    tags: ['[0-9]+.[0-9]+*']

permissions:
  contents: write

defaults:
  run:
    working-directory: documentation

env:
  CACHE_ID: unknown

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Prepare CACHE_ID
        run: echo "CACHE_ID=$(date --utc '+%V')" >>"${GITHUB_ENV}"

      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.CACHE_ID }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Python dependencies
        run: pip install mkdocs-material==9.5.4

      - name: Deploy documentation
        run: mkdocs gh-deploy --strict --force
