name: Generic Executor

on:
  workflow_call:
    inputs:
      # Set to true if you need `qemu`.
      install-qemu:
        required: false
        type: boolean
        default: false

      # Set to true if you need `sccache`.
      install-sccache:
        required: false
        type: boolean
        default: false

      # Set to true if you need `cargo-audit`.
      install-cargo-audit:
        required: false
        type: boolean
        default: false

      # Provide a command that is run in the end.
      command:
        required: true
        type: string

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: code

jobs:
  generic-execute:
    name: Run
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and mold
        run: |
          # RUST ------------------------------------------------------------------------

          (
            RUSTUP_PARAMETERS=('--quiet' '-y' '--default-toolchain' 'none' '--profile' 'minimal' '--no-update-default-toolchain')
            [[ ${#} -eq 0 ]] || readarray -t -d ' ' RUSTUP_PARAMETERS < <(printf "%s" "${*}")
            curl -sSfL 'https://sh.rustup.rs' | sudo sh -s -- "${RUSTUP_PARAMETERS[@]}"
          )

          # MOLD ------------------------------------------------------------------------

          (
            MOLD_VERSION='2.4.0'
            MOLD_DIR="mold-${MOLD_VERSION}-$(uname -m)-linux"

            cd /tmp
            curl -sSfL "https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/${MOLD_DIR}.tar.gz" | tar xz

            sudo cp "${MOLD_DIR}/bin/mold" /usr/local/bin/
            sudo cp "${MOLD_DIR}/lib/mold/mold-wrapper.so" /usr/local/bin/
            sudo ln -s /usr/local/bin/mold /usr/local/bin/ld.mold
          )

      - name: Install QEMU
        if: inputs.install-qemu
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends qemu-system-riscv64
          qemu-system-riscv64 --version

      - name: Install sccache
        if: inputs.install-sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Setup sccache
        if: inputs.install-sccache
        run: |
          echo 'SCCACHE_GHA_ENABLED=true' >>"${GITHUB_ENV}"
          echo 'RUSTC_WRAPPER=sccache' >>"${GITHUB_ENV}"
          sccache --version

      - name: Install cargo-audit
        if: inputs.install-cargo-audit
        run: |
          cargo install cargo-audit
          cargo-audit --version

      - name: Run command (with `sccache`)
        if: inputs.install-sccache
        env:
          SCCACHE_GHA_ENABLED: 'true'
          RUSTC_WRAPPER: sccache
        run: ${{ inputs.command }}

      - name: Run command (without `sccache`)
        # we need the `${{ }}` here because `!` is reserved in YAML
        if: ${{ ! inputs.install-sccache }}
        run: ${{ inputs.command }}
