---
name: Kernel Code Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/kernel-tests.yml
      - kernel/**
    branches: ['**']
  push:
    paths: [kernel/**]
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  linting:
    name: Lint the kernel code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly-2022-01-01
          override: true
          components: rustfmt, clippy

      - name: Install Rustup Components
        run: rustup component add rust-src llvm-tools-preview

      - name: Run all kernel-related checks
        run: ./scripts/test_kernel.sh --is-ci check

  unit-and-integration-tests:
    name: Run all unit- and integration-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly-2021-12-10
          override: true

      - name: Install Rustup Components
        run: rustup component add rust-src llvm-tools-preview

      - name: Install QEMU
        run: sudo apt update && sudo apt install qemu-system-x86

      - name: Print QEMU version
        run: qemu-system-x86_64 --version

      - name: Run `cargo test`
        run: ./scripts/test_kernel.sh --is-ci test
