---
name: Linting

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ['**']

jobs:
  linting:
    name: Run
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code base
        uses: super-linter/super-linter/slim@v5.6.1
        env:
          # TODO https://github.com/marketplace/actions/super-linter#add-super-linter-badge-in-your-repository-readme
          LOG_LEVEL: NOTICE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: true


          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
