---
name: Linting

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches: ['*']
    types: ['synchronize']
  push:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint against GitHub's Super-Linter
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: github/super-linter/slim@v4.8.4
        env:
          LOG_LEVEL: WARNING
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.base_ref }}
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false

          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_JSCPD_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSCPD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
