---
name: Security Audit

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - kernel/**/Cargo.toml
      - kernel/**/Cargo.lock
      - .github/workflows/security.yml
  schedule:
    - cron: 0 0 * * 6

defaults:
  run:
    shell: bash
    working-directory: kernel

jobs:
  cargo-audit:
    name: Audit Cargo.lock
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly-2022-02-12
          override: true

      - name: Install `cargo audit`
        run: cargo install cargo-audit

      - name: Run `cargo audit`
        run: cargo audit --deny warnings
