---
name: Security Audit

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - modules/**/Cargo.toml
      - modules/**/Cargo.lock
  schedule:
    - cron: 0 0 * * 6

defaults:
  run:
    shell: bash
    working-directory: modules

jobs:
  cargo-audit:
    name: Audit Cargo.lock
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly-2021-12-02
          override: true

      - name: Install `cargo audit`
        run: cargo install cargo-audit

      - name: Run `cargo audit`
        run: cargo audit --deny warnings
