---
name: Handle Stalled

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  stale:
    name: Close stale issues
    runs-on: ubuntu-20.04
    steps:
      - name: Close stale issues
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 20
          days-before-close: 10

          exempt-issue-labels: stale-bot/ignore
          stale-issue-label: meta/stale
          stale-issue-message: |
            This issue has become stale because it has been open for 20 days without activity.
            This issue will be closed in 10 days automatically unless:
            - a maintainer removes the `meta/stale` label or adds the `stale-bot/ignore` label
            - new activity occurs, such as a new comment
          close-issue-label: meta/closed due to age or inactivity
          close-issue-message: >
            This issue was closed due to inactivity.
          exempt-pr-labels: stale-bot/ignore
          stale-pr-label: meta/stale
          stale-pr-message: |
            This pull request has become stale as it has been open for 20 days without activity.
            This pull request will be closed in 10 days automatically unless:
            - a maintainer removes the `meta/stale` label or adds the `stale-bot/ignore` label
            - new activity occurs, such as a new comment
          close-pr-label: meta/closed due to age or inactivity
          close-pr-message: >
            This PR was closed due to inactivity.
