---
name: Unit- and Integration-Tests

on: [push, pull_request] # yamllint disable-line rule:truthy

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup All Dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setting up QEMU (1/2)
        run: >
          sudo apt-get -qq --fix-missing update &&
          sudo apt-get -qq -y --no-install-recommends install
          qemu-system-x86 &>/dev/null

      - name: Setting up QEMU (2/2)
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64

      - name: Installing Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Installing Toolchain
        run: rustup toolchain install $(<rust-toolchain)
      - name: Installing Rustup Components
        run: rustup component add llvm-tools-preview
      - name: Install Cargo Components
        run: cargo install cargo-xbuild bootimage

  ui_check:
    name: Run Unit- and Integration-Tests
    runs-on: ubuntu-20.04
    needs: dependency_setup
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Toolchain
        run: rustup override set $(<rust-toolchain)
      - name: Running Unit- & Integration-Tests
        run: cargo test
